### ISSUE TITLE
Bollinger Bands standard deviation calculation is different from other implementations

### ISSUE THREAD

**Issue by rene-post** [cinar/indicator#102]
The Bollinger Bands upper band and lower band seem to be too wide.

Below is a screenshot of the visualisation tool I'm working on:

![Screenshot 2022-06-20 at 23 19 08](https://user-images.githubusercontent.com/1306351/174679083-408414dd-af9f-4cda-8454-89caf21641c7.png)

In white are the bands computed by your BollingerBands sma(20) and standard deviation functions.

Your sma(20) seems to match up on top of my sma(20) calculation correctly.

In red and green are the upper and lower bands calculated by me based on code I derived from [go-talib](https://github.com/markcheno/go-talib). 

The standard deviation (2.0) output does **not** match go-talib and therefore also **not** my implementation.
A quick inspection seems to suggest it also does **not** match Trading View's Bollinger Bands implementation.

Below is the code I use, feel free to use if you're so inclined. It's MIT licensed.

```go
// BBands - Bollinger Bands
// BBands(upperband, middleband, lowerband, close, periods=20, nbdevup=2, nbdevdn=2, ma=Sma)
func BBands(upperband, middleband, lowerband, closing []float64, periods int, nbdevup, nbdevdn float64, ma MA) {
	ma(middleband, closing, periods)
	StdDev(upperband, closing, periods, 1.0)
	for i, mb := range middleband {
		sd := upperband[i]
		upperband[i] = mb + nbdevup*sd
		lowerband[i] = mb - nbdevdn*sd
	}
}

// StdDev - Standard Deviation
func StdDev(dst, src []float64, periods int, nbdev float64) {
	Var(dst, src, periods)
	for i, v := range dst {
		if v < 0.00000000000001 {
			dst[i] = 0.0
		} else {
			dst[i] = nbdev * math.Sqrt(v)
		}
	}
}

// Var - Variance
func Var(dst, src []float64, periods int) int {
	if periods > 0 {
		sum, sum2 := 0.0, 0.0
		for i, v := range src {
			sum, sum2 = sum+v, sum2+v*v
			if i < (periods - 1) {
				dst[i] = 0.0
			} else {
				dst[i] = sum2/float64(periods) - (sum/float64(periods))*(sum/float64(periods))
				w := src[i-(periods-1)]
				sum, sum2 = sum-w, sum2-w*w
			}
		}
		return len(src)
	}
	return 0
}
```

**Comment by rene-post** [comment]
I've got the Bollinger on Bollinger Bands book in hardcover and your implementation seem to match the formula as described in the book. So perhaps go-talib is incorrect? I'll also run some more comparisons to investigate further. (Unrelated; I love what you are doing here with the indicator package!)

**Comment by rene-post** [comment]
Some new developments. I've been studying the "Bollinger on Bollinger Bands" book, chapter 7 page 52 "Construction" and the standard deviation population formula described there translates into something like the following:

```go
// Standard deviation.
func Std(period int, values []float64) []float64 {
	result := make([]float64, len(values))
	sma := Sma(period, values)

	for i := range values {
		result[i] = 0.0
		if i >= period-1 {
			sum := float64(0)
			for k := i - (period - 1); k <= i; k++ {
				sum += (values[k] - sma[i]) * (values[k] - sma[i])
			}
			result[i] = math.Sqrt(sum / float64(period))
		}
	}

	return result
}
```
So, I know this is not really very efficient, but plugging this into my visualiser matches up the bands correctly with my go-talib based implementation. Note also that, I plug in zeroes here for 'i' in range [0..period-2]. The result at 'i' = period-1 has the first valid result. This differs from your approach where the result is a best effort result calculation in the warm-up period.

**Comment by cinar** [comment]
This is definitely much more similar to the current implementation. Yes, the second loop is ugly, but I think that is also what is making this one more correct compared to the existing implementation. I can probably put a math.Pow((values[k] - sma[i]), 2.0) there, but other than that this looks very clean.

Would you like to send a pull request or I should just copy it. Both works for me.

Regarding the zeros for the warm up period, you are right, I made the rest of the functions here to produce numbers during the warm up period. I am still going back and forth on that one, as it seems to be causing other issues. Perhaps something I should change for all other functions. May be we do it for the RSI, and then I'll try to apply it to the other functions too.

**Comment by rene-post** [comment]
Please copy it, I’ll try to submit a PR the next time.
W.r.t. the explicit expansions of the math.Pow, that was something that was suggested by a visual studio code extension. Don’t know if it is actually faster that way.

So, until now, I was working on a ta lib derived from go-talib sources but with the source cleaned up. My initial improvements were also doing a nice convergence during the warm-up period. I ran into trouble with that in functions that were using those warmup results and skewing/offsetting other indicators. So now I was looking at actually setting those initial values tot NaN to indicate they are not to be used. Also when e.g. backtesting a strategy there may be some arbitrary buy and sell actions generated when the algorithm is warming up, also skewing the performance measurement of the strategy. Anyway my strategy wrapper that integrates into my bot code explicitly returns the maximum number of warmup periods and I then ignore any actions suggested during the warmup.
