### ISSUE TITLE
Getting invalid SMA's

### ISSUE THREAD

**Issue by mrkarn007** [cinar/indicator#128]
**Describe the bug**
I encountered an issue with the Simple Moving Average (SMA) calculation logic, which resulted in incorrect initial values in the SMA for certain input slices for indices less than period val

**To Reproduce**
1. Input a specific slice and period value, for example: [2, 4, 6, 8, 10], 2 into the SMA calculation method.
2. Perform the SMA calculation using the software/library.
3. Observe the output.

**Expected behavior**
The expected behavior is that the initial values of the SMA calculation should be set to 0.0, while the subsequent values should match the SMA calculation results. For the input slice [2, 4, 6, 8, 10], the expected output should be [0.0, 3.0, 5.0, 7.0, 9.0].

**Screenshots**
I have added screenshot of code which was causing the issue.
<img width="432" alt="Screenshot 2023-10-28 at 1 32 06 PM" src="https://github.com/cinar/indicator/assets/147133102/648c7ef9-633a-4e37-8ac2-f6cb7669717d">

**Desktop (please complete the following information):**
- MacOS
- Programming Language: Go
- Version of Software/Library:1.20.5

**Comment by cinar** [comment]
Release V2 will no longer return any values until the period is full. Closing this issue. Please let me know if you see any problems with the release V2 on this issue.
