### ISSUE TITLE
module github.com/cinar/indicator/v2@latest found (v2.0.1), but does not contain package github.com/cinar/indicator/v2

### ISSUE THREAD

**Issue by heiningair** [cinar/indicator#150]
**Describe the bug** + **To Reproduce**
When I want to upgrade from v1 to v2, I did the following steps:

1. cleared go mod cache: "go clean -modcache"
2. exchanged all appearances of the the old lib path "github.com/cinar/indicator" with the "github.com/cinar/indicator/v2" version
3. did a "go get github.com/cinar/indicator/v2"
4. "go mod tidy" gives me the following output:

---> 
go: finding module for package github.com/cinar/indicator/v2
go: github.com/heiningair/my-project/cmd/api imports
        github.com/cinar/indicator/v2: module github.com/cinar/indicator/v2@latest found (v2.0.1), but does not contain package github.com/cinar/indicator/v2

**Expected behavior**

I would expect it to download the package (which it does! It is in golangs mod cache at this point) and then NOT complain about the package github.com/cinar/indicator/v2 not being contained

**Comment by cinar** [comment]
Just did something quick as a new project:

```bash
go mod init github.com/cinar/x
```

Added a quick file:

main.go:
```golang
package main

import (
        "fmt"

        "github.com/cinar/indicator/v2/trend"
)

func main() {
        macd := trend.NewMacd[float64]()
        fmt.Printf("%d", macd.IdlePeriod())
}
```

Go mod tidy seems to be working for me, but I'm on Go 1.22.1, I  wonder if that plays a role.

```bash
$ go mod tidy
go: finding module for package github.com/cinar/indicator/v2/trend
go: found github.com/cinar/indicator/v2/trend in github.com/cinar/indicator/v2 v2.0.1
```

Would you mind trying with an empty project to see if it will make a difference?

**Comment by heiningair** [comment]
@cinar thanks for the quick reply!

yeah indeed tricky sometimes..

I will try your suggestion with a new project and report what i`ve found

**Comment by heiningair** [comment]
ok.. thanks, it seems to work with a new project. investigating further from here. I might be missing something in my other project then..

**Comment by heiningair** [comment]
I think I got it now.. I had a few lines in there still using the library like in v1

example -> indicator.Ema(...)

this seems to prevent it from pointing to the actual dep when doing a "go mod tidy"

**Comment by cinar** [comment]
Ah, that makes sense. Yes, v2 is a totally breaking change. I originally
wanted to have a v1 compatibility layer to make the migration easier, but
couldn't get to that.

I'm glad that you are unblocked. Please let me know how v2 works for you.

**Comment by heiningair** [comment]
I will definitely let you know as soon as I migrated completely.

As you mentioned, these are breaking changes, but at first glance, it looks a lot nicer! I waited for this for a while already  ;)

Thx for your work :)
