### ISSUE TITLE
Snapshot Volume also float64 instead of int64 !?

### ISSUE THREAD

**Issue by heiningair** [cinar/indicator#157]
**Is your feature request related to a problem? Please describe.**
When using indicators, like e.g. trend.NewVwma[float64]() and executing a Compute on it, channels need to be passed in (per Type definition) they need to match float64 in this case for closings and volume.

**Describe the solution you'd like**
When giving the Volume in the Snapshot type a float64 value instead of the int64 it would make things easier to work with, wouldnt it?

**Comment by cinar** [comment]
Let me see.. I should be able to change it.

**Comment by heiningair** [comment]
that would be awesome. I assume that various ohlc structures out there handling that differently, but for calculations within this library structure aka the indicators, it might be easier...

**Comment by HouzuoGuo** [comment]
Thanks cinar!

Changing the volume data type to float64 would be immensely useful for assets traded in fractions (e.g. cryptocurrencies).

**Comment by cinar** [comment]
I'll take care of it today quickly. I feel it will be an easy one.

**Comment by cinar** [comment]
I made the change. You can use it starting from [Release v2.1.0](https://github.com/cinar/indicator/releases/tag/v2.1.0). Please let me know if I missed anything.
