### ISSUE TITLE
Option to set the time format for the reports

### ISSUE THREAD

**Issue by heiningair** [cinar/indicator#158]
**Is your feature request related to a problem? Please describe.**
As I understand this the report assumes the time format should be truncated to a per day level ("2006-01-02"), is that correct?

starting at line 104 - line 110
```
            data.addRow([
                new Date("{{ .Format "2006-01-02" }}"),
                {{ range $.Columns }}
                {{ .Value }},
                {{ end }}
            ]);
            {{ end }}
```

Does this mean it wouldnt work for data that has another resolution than days, e.g. hourly, or 1-minute data?

**Describe the solution you'd like**
a way to set another format for the dates, so that it can be any type of date resolution. Maybe make it configurable on the Backtest instance?!

would be super cool to have that

**Comment by cinar** [comment]
This a great idea. I will make it configurable.

**Comment by cinar** [comment]
You can use this starting with [v2.0.5](https://github.com/cinar/indicator/releases/tag/v2.0.5). Please re-open if it doesn't work as you expected. Thank you for the feature request!
