### ISSUE TITLE
The comment for helper.Shift is slightly wrong.

### ISSUE THREAD

**Issue by Vextasy** [cinar/indicator#166]
The example in the comment reads:

```go
//	input := helper.SliceToChan([]int{2, 4, 6, 8})
//	output := helper.ChanToSlice(input, 4, 0))
//	fmt.Println(helper.ChanToSlice(output)) // [0, 0, 0, 0, 2, 4, 6, 8]
```
but should probably be:
```go
//	input := helper.SliceToChan([]int{2, 4, 6, 8})
//	output := helper.Shift(input, 4, 0)
//	fmt.Println(helper.ChanToSlice(output)) // [0, 0, 0, 0, 2, 4, 6, 8]
```
There are two things to fix here: a) the function name and b) remove the extra trailing bracket.

**Comment by cinar** [comment]
Thank you very much for reporting it! I just fixed it. I am trying to find a way to check those examples in the comments somehow.
