### ISSUE TITLE
Ability to control library logs/output

### ISSUE THREAD

**Issue by ibyter** [cinar/indicator#224]
Currently when running a backtest:

```Go
...
backtest.Run()
```

Logs are printed alongside my app logs:
```
{"time":"2024-09-17T22:35:44.859099+03:00","level":"INFO","msg":"computing strategies outcomes","logger":"stockstrategy","stock":1628,"datesCount":2}
2024/09/17 22:35:44 Backtesting ABC...
```

my logs are structured `{"time"..`,  and get mixed with library logs `2024/09/17 22:35:44 Backtesting...` 

It would be best if we can control the logger inside the library

**Comment by cinar** [comment]
Good point. Are you using log/slog or the log/Logger?

**Comment by cinar** [comment]
Please check the #225 PR to see if this will work for your use case.

**Comment by ibyter** [comment]
Yes I am using slog package, and PR looks good

**Comment by cinar** [comment]
Awesome, I just merged it. You can use it from release v2.1.5. Please reopen if you run into any issues.
