### ISSUE TITLE
Handling consecutive buy actions

### ISSUE THREAD

**Issue by ibyter** [cinar/indicator#230]
Not sure if this is a bug, or a design decision. But the `Outcome` function (https://github.com/cinar/indicator/blob/v2.1.5/strategy/outcome.go) does not handle consecutive buy actions.

**Comment by cinar** [comment]
Ah yes, that is by design. The Outcome function will execute the first Buy
action and will wait for a Sell action while ignoring everything in between.

For example:

Input actions [Sell, Hold, Buy, Buy, Sell] gets handles as [Hold, Hold,
Buy, Hold, Sell].

What is your use case?

**Comment by ibyter** [comment]
Well in my case, the actions I receive from the strategy will be sent to the broker and executed on the market. However, the outcome is computing a subset of the actions received.

So there is this a discrepancy between the actual outcome, and the outcome competed locally.

**Comment by cinar** [comment]
Unfortunately, it isn't suitable for your specific needs. It currently uses the closing price and recommended action, which can differ significantly from the actual price you've purchased.

Consider it more of a strategy tester for now. For your purposes, a portfolio tracker would be more helpful. I'm planning to add that feature in the future.
