### ISSUE TITLE
Are KDJ metrics available

### ISSUE THREAD

**Issue by iwctwbai** [cinar/indicator#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cinar** [comment]
Is this the correct calculation for it?

https://ichihedge.wordpress.com/2017/03/22/indicator-calculating-kdj/

**Comment by iwctwbai** [comment]
I think it's ok
And you can refer to https://github.com/joeguo/indicator/blob/master/kdj.go

**Comment by cinar** [comment]
Please let me know if it doesn't work.

**Comment by iwctwbai** [comment]
It worked without any problems
