### ISSUE TITLE
MoneyFlowIndex values well above 100

### ISSUE THREAD

**Issue by natemccallum** [cinar/indicator#41]
**Describe the bug**
Using the Money Flow Index and I am consistently seeing values well in excess of 100. 

**To Reproduce**

With these assets I get a MFI of  around 283.

High|Low|Close|Vol
-- | -- | -- | --
2390.9 | 2373.15 | 2373.39 | 1621
2386.3 | 2370 | 2382.47 | 1387
2395.33 | 2380.77 | 2394.4 | 1444
2399 | 2384.28 | 2387.51 | 1298
2402.46 | 2387.46 | 2395.64 | 1629
2401.15 | 2385.02 | 2389.47 | 1598
2421.98 | 2383.18 | 2410.24 | 2311
2430.31 | 2408.39 | 2425.37 | 2934
2426.33 | 2410.59 | 2422.33 | 2128
2434.93 | 2420.89 | 2430.29 | 1823
2470.83 | 2428.92 | 2465.76 | 5078
2483.36 | 2456.77 | 2466.27 | 6693
2467.19 | 2437.65 | 2440.07 | 3960
2450.72 | 2440.87 | 2445.85 | 1927

In looking through through the code it appears when you keep the negative values, you are keeping them as negatives thus their sum is negative when entering the formula for Money Ratio. It's my understanding Money Ratio takes a positive for both Positive Money Flow and for Negative Money Flow thus never yielding a negative ratio. I calculate the MFI should be around 58 for those assets. I'm new to these strategies so apologies if I've got something wrong here.

Thank you for the great project, it is super insightful for my project.

**Comment by cinar** [comment]
I think you are right, that seems to be the problem. I changed the sign of those, and the numbers are within the range. If they also look good to you, I'll merge this change.

High | Low | Close | Vol | MFI  
-|-|-|-|-
2390.9 | 2373.15 | 2373.39 | 1621 | 100  
2386.3 | 2370 | 2382.47 | 1387 | 53.88
2395.33 | 2380.77 | 2394.4 | 1444 | 51.12
2399 | 2384.28 | 2387.51 | 1298 | 52.66
2402.46 | 2387.46 | 2395.64 | 1629 | 55.71
2401.15 | 2385.02 | 2389.47 | 1598 | 50.51
2421.98 | 2383.18 | 2410.24 | 2311 | 59.25
2430.31 | 2408.39 | 2425.37 | 2934 | 100
2426.33 | 2410.59 | 2422.33 | 2128 | 57.98
2434.93 | 2420.89 | 2430.29 | 1823 | 0
2470.83 | 2428.92 | 2465.76 | 5078 | 73.79
2483.36 | 2456.77 | 2466.27 | 6693 | 100
2467.19 | 2437.65 | 2440.07 | 3960 | 63.02
2450.72 | 2440.87 | 2445.85 | 1927 | 0

**Comment by natemccallum** [comment]
Hmmm. When I run it with those values I get:

High | Low | Close | Vol | MFI
-- | -- | -- | -- | --
2390.9 | 2373.15 | 2373.39 | 1621 | 100
2386.3 | 2370 | 2382.47 | 1387 | 53.884998
2395.33 | 2380.77 | 2394.4 | 1444 | 68.888204
2399 | 2384.28 | 2387.51 | 1298 | 53.300054
2402.46 | 2387.46 | 2395.64 | 1629 | 63.645476
2401.15 | 2385.02 | 2389.47 | 1598 | 52.296425
2421.98 | 2383.18 | 2410.24 | 2311 | 62.119198
2430.31 | 2408.39 | 2425.37 | 2934 | 70.011701
2426.33 | 2410.59 | 2422.33 | 2128 | 60.826077
2434.93 | 2420.89 | 2430.29 | 1823 | 54.659774
2470.83 | 2428.92 | 2465.76 | 5078 | 64.728457
2483.36 | 2456.77 | 2466.27 | 6693 | 72.749002
2467.19 | 2437.65 | 2440.07 | 3960 | 64.185176
2450.72 | 2440.87 | 2445.85 | 1927 | 60.710993

When I do the calculation in Excel I also get these numbers.

The only thing I changed was in keepNegatives. I multiplied the kept value by -1. Not sure if this change breaks anything else, but...
```
func KeepNegatives(values []float64) []float64 {
	result := make([]float64, len(values))

	for i := 0; i < len(values); i++ {
		if values[i] < 0 {
			result[i] = values[i] * -1
		} else {
			result[i] = 0
		}
	}

	return result
}
```

Here is my test code....

```
	a := indicator.Asset{
		Date:    []time.Time{time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now(),time.Now()},
		Opening: []float64{},
		Closing: []float64{2373.39,2382.47,2394.4,2387.51,2395.64,2389.47,2410.24,2425.37,2422.33,2430.29,2465.76,2466.27,2440.07,2445.85},
		High:    []float64{2390.9,2386.3,2395.33,2399.0,2402.46,2401.15,2421.98,2430.31,2426.33,2434.93,2470.83,2483.36,2467.19,2450.72},
		Low:     []float64{2373.15,2370.0,2380.77,2384.28,2387.46,2385.02,2383.18,2408.39,2410.59,2420.89,2428.92,2456.77,2437.65,2440.87},
		Volume:  []int64{1621,1387,1444,1298,1629,1598,2311,2934,2128,1823,5078,6693,3960,1927},
	}
	moneyFlowIndex := MoneyFlowIndexNew( 14,
		a.High,
		a.Low,
		a.Closing,
		a.Volume)

	for i,_:=range moneyFlowIndex {
		fmt.Printf("%f,%f,%f,%d,%f\n", a.High[i], a.Low[i], a.Closing[i],a.Volume[i],moneyFlowIndex[i])
	}
```

**Comment by cinar** [comment]
It looks like I computed my numbers with period = 2, and yours are with 14. After made the change, I am getting the same numbers. I added a new test with your numbers under TestMoneyFlowIndex2. Looks like this is working now, thank you again for filing the bug and helping me to get it fixed.

**Comment by natemccallum** [comment]
No Problem. Thanks again for the project and prompt response. Best regards.
