### ISSUE TITLE
Stochastic Oscillator problem

### ISSUE THREAD

**Issue by Wraken** [cinar/indicator#69]
Hi ! 

I think there is a mistake in the Stochastic Oscillator calculation. 
From [this](https://school.stockcharts.com/doku.php?id=technical_indicators:stochastic_oscillator_fast_slow_and_full) site, it seems that the `multiplyBy` is not in the right place. 

This : 
`k := divide(substract(closing, lowestLow14), multiplyBy(substract(highestHigh14, lowestLow14), float64(100)))`

Should be : 
`k := multiplyBy(divide(substract(closing, lowestLow14), substract(highestHigh14, lowestLow14)), float64(100))`

I might be wrong but results from this change looks nice to me ! 

And thank you for this package, I love it :D

**Comment by cinar** [comment]
Hi Wraken, Thank you very much for filing a bug. I think you are right, this seems to be an error. I changed it as you have suggested. Also didn't have any test cases before, so added one. Could you take a look to verify it? It is in the issue-69 branch now.

**Comment by Wraken** [comment]
Your commit seems good ! Tests are fine too ! 

Thanks for your quick fix.

**Comment by cinar** [comment]
Made a new release.
