### ISSUE TITLE
Lower Acceleration Band Value is incorrect

### ISSUE THREAD

**Issue by liamwh** [cinar/indicator#7]
**Maths for acceleration lower band appears to be incorrect**
![image](https://user-images.githubusercontent.com/23312359/133934509-5673a641-f901-4d00-8d83-40df323b7e8e.png)

**Expected:**
1m:
![image](https://user-images.githubusercontent.com/23312359/133934607-af7dd603-99e6-4432-8a70-6968a99e8357.png)

15m:
![image](https://user-images.githubusercontent.com/23312359/133934620-b7f15af8-8293-4916-a9c2-3f52eb5b2e00.png)

1h:
![image](https://user-images.githubusercontent.com/23312359/133934627-f21d38d3-05b7-4d19-8a57-5faa4506b71d.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/23312359/133934545-1ccff6ec-6cc5-450d-a976-6a27cb4a163c.png)
+
![image](https://user-images.githubusercontent.com/23312359/133934564-1d03f980-49cf-49c2-9ce4-cd7084e45c86.png)

**Expected behavior**
Formula to calculate the lower band would correlate with the following pinescript:
![image](https://user-images.githubusercontent.com/23312359/133934589-f94f0011-3052-4a95-8337-c871ab437339.png)

**Additional context**
Just wanted to say I'm loving using the package, thanks for your great work Cinar! I would be absolutely willing to contribute but maths really isn't my strong suit 😅

**Comment by cinar** [comment]
Thank you very much Liam for filing the issue. Let me compare the calculations and fix it. I can definitely use your help to validate it.

**Comment by liamwh** [comment]
> Thank you very much Liam for filing the issue. Let me compare the calculations and fix it. I can definitely use your help to validate it.

No problem, just let me know which branch to pull and I'll happily share the results of my testing! 👍

Cheers Cinar!

**Comment by liamwh** [comment]
For what it's worth, as a cheat / workaround, I've written this:

```go
func AccelerationBands(high, low, close []float64) ([]float64, []float64, []float64) {
	checkSameSize(high, low, close)

	k := addBy(multiplyBy(divide(substract(high, low), add(high, low)), 4), 1)

	upperBand := Sma(20, multiply(high, k))
	middleBand := Sma(20, close)
	var lowerBand []float64
	for i, upperValue := range upperBand {
		lowerBand = append(lowerBand, (middleBand[i] - (upperValue - middleBand[i])))
	}

	return upperBand, middleBand, lowerBand
}
```

**Comment by cinar** [comment]
Hi Liam, I found a mistake in lower band calculation. Could you try with v1.2.4 to see if it fixed the problem for your calculation?

**Comment by liamwh** [comment]
> Hi Liam, I found a mistake in lower band calculation. Could you try with v1.2.4 to see if it fixed the problem for your calculation?

It's perfect now, great work and thanks again Cinar!

**Comment by cinar** [comment]
Hi Liam, you are very welcome, I am glad to hear that it worked.

I am trying to identify the next set of technical indicators to include to the module. If there any specific ones that you like to see included please let me know by filing an issue. Many thanks!
