### ISSUE TITLE
FOSC / CFO Indicator

### ISSUE THREAD

**Issue by liamwh** [cinar/indicator#9]
**Describe the solution you'd like**
FOSC (aka CFO) indicator in the package, like [this](https://github.com/technicalviking/tulipindicators/blob/master/fosc.c) or the following pinescript:
```pine
//@version=2
////////////////////////////////////////////////////////////
// The Chande Forecast Oscillator developed by Tushar Chande The Forecast 
// Oscillator plots the percentage difference between the closing price and 
// the n-period linear regression forecasted price. The oscillator is above 
// zero when the forecast price is greater than the closing price and less 
// than zero if it is below.
////////////////////////////////////////////////////////////
strategy(title="Chande Forecast Oscillator", shorttitle="CFO")
Length = input(14, minval=1)
Offset = input(0)
hline(0, color=black, linestyle=line)
xLG = linreg(close, Length, Offset)
xCFO = ((close -xLG) * 100) / close
plot(xCFO, color=red, title="CFO")
```

Formula also here:
https://www.stockmaniacs.net/chande-forecast-oscillator/

And here:
https://www.fmlabs.com/reference/default.htm?url=ForecastOscillator.htm

**Comment by liamwh** [comment]
I've tried this but am not getting values that correspond with TradingView:

```go
timeSeriesForecast := talib.Tsf(closePrices, periods)

var fosc []float64
for i, close := range closePrices {
  result := close - timeSeriesForecast [i]
  fosc = append(fosc, (result*100)/close)
}
```

My results:
15m FOSC: 2.06172332 (TradingView -0.591)
1h FOSC: 0.68674927 (TradingView -0.307)

**Comment by cinar** [comment]
Hi Liam, I added the implementation for Chande Forecast Oscillator. Could you take a look issue-9 branch to check if it works properly? I wasn't able to find a site that can calculate it to compare the results. Many thanks!
